### ISSUE TITLE
nfd: redundant 'nrd' service

### ISSUE THREAD

**Issue by yoursunny** [named-data/ppa-packaging#5]
`nrd` daemon is removed as of NFD 0.3.1 release, but the `nfd` package still installs `/etc/init/nrd.conf` which is redundant.

`/usr/bin/nrd` may also be unnecessary.

**Comment by yoursunny** [comment]
This bug persists in 0.3.3-ppa1~trusty.

**Comment by cawka** [comment]
This bug should have been addressed already.  At least I don't see that nfd has nrd.upstart.

As part of ed9586b0dd648668799ed883e11de6982c24371 the other part of this issue has been addressed as well: make sure all NFD-dependent daemons start after nfd, not nrd as it was instructed previously.

**Comment by yoursunny** [comment]
As of 0.3.3-ppa4~trusty, `/etc/init/nrd.conf` is gone, but `/usr/bin/nrd` still exists.
